#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nodeenv
Version  : 1.2.0
Release  : 26
URL      : http://pypi.debian.net/nodeenv/nodeenv-1.2.0.tar.gz
Source0  : http://pypi.debian.net/nodeenv/nodeenv-1.2.0.tar.gz
Summary  : Node.js virtual environment builder
Group    : Development/Tools
License  : BSD-3-Clause
Requires: nodeenv-bin
Requires: nodeenv-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
===========================
        
        ``nodeenv`` (node.js virtual environment) is a tool to create 
        isolated node.js environments.
        
        It creates an environment that has its own installation directories, 
        that doesn't share libraries with other node.js virtual environments.
        
        Also the new environment can be integrated with the environment which was built
        by virtualenv_ (python).

%package bin
Summary: bin components for the nodeenv package.
Group: Binaries

%description bin
bin components for the nodeenv package.


%package python
Summary: python components for the nodeenv package.
Group: Default

%description python
python components for the nodeenv package.


%prep
%setup -q -n nodeenv-1.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1501701573
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1501701573
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/nodeenv

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
