#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nodeenv
Version  : 1.1.2
Release  : 23
URL      : http://pypi.debian.net/nodeenv/nodeenv-1.1.2.tar.gz
Source0  : http://pypi.debian.net/nodeenv/nodeenv-1.1.2.tar.gz
Summary  : Node.js virtual environment builder
Group    : Development/Tools
License  : BSD-3-Clause
Requires: nodeenv-bin
Requires: nodeenv-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Node.js virtual environment
===========================
``nodeenv`` (node.js virtual environment) is a tool to create
isolated node.js environments.

%package bin
Summary: bin components for the nodeenv package.
Group: Binaries

%description bin
bin components for the nodeenv package.


%package python
Summary: python components for the nodeenv package.
Group: Default

%description python
python components for the nodeenv package.


%prep
%setup -q -n nodeenv-1.1.2

%build
export LANG=C
export SOURCE_DATE_EPOCH=1487186365
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1487186365
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/nodeenv

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
